
TABLE_NAME="SXTDEMO.STOCKS"
ACCESS_TYPE="public_read"
RESOURCE_NAME="SXTDEMO.STOCKS"
RESOURCE_TYPE="TABLE"
RESOURCE_NAME_TEMPLATE="SXTDEMO.STOCKS"
RESOURCE_PRIVATE_KEY="1234PRIVATE"
RESOURCE_PUBLIC_KEY="1234P5UBLIC"
# -- BISCUITS:
READ_BISCUIT_TOKEN="ASDF1234"
LOAD_BISCUIT_TOKEN=""
ADMIN_BISCUIT_TOKEN="ASDF1234"
# -- SQL:
CREATE_DDL_TEMPLATE=$(cat << __DOCSTRING_BOUNDRY__
    CREATE TABLE SXTDEMO.STOCKS 
    (Symbol         VARCHAR
    ,Stock_Date     DATE 
    ,Stock_Open     DECIMAL
    ,Stock_High     DECIMAL
    ,Stock_Low      DECIMAL
    ,Stock_Close    DECIMAL
    ,Stock_AdjClose DECIMAL
    ,Stock_Volume   BigInt
    ,PRIMARY KEY (Symbol,Stock_Date)
    ) {with_statement}
__DOCSTRING_BOUNDRY__
)
